### ISSUE TITLE
Please provide more explicit information

### ISSUE THREAD

**Issue by RubickH** [yangxuntu/SGAE#1]
Hi!
I am very interested in your work and run eval_mem.py to evaluate the two models.
However, I find that the CIDEr score of these two models are 0.313 and 0.470 respectively.
I also try to run train_mem.py to train new models, yet notice that some .npz files might be missing. 
Could you please provide more explicit information about the settings for training and evaluation?
Great Thanks!

**Comment by yangxuntu** [comment]
I will provide the details today.
