### ISSUE TITLE
faster r-cnn features

### ISSUE THREAD

**Issue by tuyunbin** [yangxuntu/SGAE#10]
Hi, could you kindly offer the faster rcnn features with google driver or baidu driver, because the link you offered is invalid. Thank you!
<Error>
<Code>UserProjectMissing</Code>
<Message>
Bucket is a requester pays bucket but no user project provided.
</Message>
<Details>
Bucket is Requester Pays bucket but no billing project id provided for non-owner.
</Details>
</Error>

**Comment by yangxuntu** [comment]
The faster rcnn visual features are provided by the link https://github.com/peteanderson80/bottom-up-attention, I still can download it.

**Comment by tuyunbin** [comment]
Thank you!

**Comment by ydyrx-ldm** [comment]
hi,
can i get the feature  bottom up with resnet152

**Comment by yangxuntu** [comment]
You mean that you want to use resnet-152 feature for captioning? I think the features from bottom-up top-down are better for captioning.
________________________________
发件人: ydyrx-ldm ***@***.***>
发送时间: 2021年6月12日 22:33
收件人: yangxuntu/SGAE ***@***.***>
抄送: #YANG XU# ***@***.***>; Comment ***@***.***>
主题: Re: [yangxuntu/SGAE] faster r-cnn features (#10)


hi,
can i get the feature bottom up with resnet152

―

**Comment by ydyrx-ldm** [comment]
@yangxuntuThanks for your reply. It is still a bottom-up feature, but Faster RCNN is with Resnet152 as backbone rather than Resnet101. It's not just Resnet152 training

**Comment by yangxuntu** [comment]
Ok. Actually, I do not know which feature is better, but you can have a try. It is hard to judge which one is better and you have to try it and then know it.
________________________________
发件人: ydyrx-ldm ***@***.***>
发送时间: 2021年6月13日 12:39
收件人: yangxuntu/SGAE ***@***.***>
抄送: #YANG XU# ***@***.***>; Comment ***@***.***>
主题: Re: [yangxuntu/SGAE] faster r-cnn features (#10)


@yangxuntuThanks for your reply. It is still a bottom-up feature, but Faster RCNN is with Resnet152 as backbone rather than Resnet101. It's not just Resnet152 training

―

**Comment by ydyrx-ldm** [comment]
You are right, but I can't find the Faster_rcnn code for network training based on resnet152, or the generated .tsv file such as
.https://github.com/peteanderson80/bottom-up-attention，
The author seems to have used bottom-up with101
Do you have any suggestions？

**Comment by yangxuntu** [comment]
Maybe you can read the paper In Defense of Grid Features for Visual Question Answering for getting better features, this paper discusses why bottom up feature is good and then gives a better one.
________________________________
发件人: ydyrx-ldm ***@***.***>
发送时间: 2021年6月13日 15:26
收件人: yangxuntu/SGAE ***@***.***>
抄送: #YANG XU# ***@***.***>; Comment ***@***.***>
主题: Re: [yangxuntu/SGAE] faster r-cnn features (#10)


You are right, but I can't find the Faster_rcnn code for network training based on resnet152, or the generated .tsv file such as
.https://github.com/peteanderson80/bottom-up-attention，<https://github.com/peteanderson80/bottom-up-attention%EF%BC%8C>
The author seems to have used bottom-up with101
Do you have any suggestions？

―

**Comment by ydyrx-ldm** [comment]
I saw an associated code, but I'm not sure if it works？
https://github.com/MILVLG/bottom-up-attention.pytorch#pre-trained-models
Can you take a look?
Backbone has the best effect with Resnet152.
